# Site
name: "Sourabh Somani's Blog"
title: "Sourabh Somani's Blog"
description: "A personal blogging site"
meta_description: "A Personal Blogging Site"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-67527174-2'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sourabh:
    name: Sourabh
    display_name: Sourabh Somani
    email: sourabh_somani2010@hotmail.com
    web: https://www.sourabhsomani.com
    twitter: https://twitter.com/sourabh_somani
    gravatar: 2eb0f7b5b2218d6b6b81af929e3bda93
    description: "Sourabh Somani, the 3 times Microsoft MVP and 6-times C# Corner MVP, is a tech lead, contributor, International Speaker, Author, and the founder of www.PythonBabu.com. After possessing a B-Tech degree in Computer Science, he found his niche in core programming and database development. His core competencies include Mobile and web applications development using ASP.NET, Python, MVC, Node.js, C#, Java Script, jQuery, SQL Server, NoSQL, MongoDB, and Angular. With his extensive experience of several years, passion toward learning new technologies, and a zeal to give back to the developer community, Sourabh contributes his knowledge via very helpful articles and blogs on various community sites."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /recent-:num
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true